config/routes.rb
Rails.application.routes.draw do
  resources :currencies
  devise_for :users
    root 'home#index'
	get 'home/about'
	get 'home/lookup'
	post "/home/index" => 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :currencies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  def index
    @currencies = Currency.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @portfolio_currency = JSON.parse(@response)
    @profit_loss = 0
  end

  def show
    @currencies = Currency.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_currency = JSON.parse(@response)
  end

  def new
    @currency = Currency.new
  end

  def edit
  end

  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to currencies_path, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_currency
      @currency = Currency.find(params[:id])
    end

    def currency_params
      params.require(:currency).permit(:symbol, :user_id, :invested_at, :amount_owned, :name)
    end

    def correct_user
      @correct = current_user.currencies.find_by(id: params[:id])
      redirect_to currencies_path, notice: "You can only edit your own portfolio." if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	require 'net/http'
  	require 'json'
  	@url = 'https://api.coinmarketcap.com/v1/ticker/'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@lookup_coin = JSON.parse(@response)
  	@coins = JSON.parse(@response)
  	@my_coins = ["BTC", "XRP", "BTS", "XLM", "STEEM"]
  	@symbol = params[:sym]
  	if @symbol
  		@symbol = @symbol.upcase
    end

  	if @symbol == ""
  		@symbol = "Hey, you forgot to enter a currency!"
  	end


  end

  def about
  end

  def lookup
  	require 'net/http'
  	require 'json'
  	@url = 'https://api.coinmarketcap.com/v1/ticker/'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@lookup_coin = JSON.parse(@response)

  	@symbol = params[:sym]
  	if @symbol
  		@symbol = @symbol.upcase
  	end

  	if @symbol == ""
  		@symbol = "Hey, you forgot to enter a currency!"
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/currencies/_edit.html.erb
<div class="panel panel-default container-3">
  <div class="panel-heading">
    <h3 class="panel-title">Edit your <%= @currency.symbol %></h3>
  </div>
  <div class="panel-body">
    <div class="form-group">


      <%= form_with(model: currency, local: true) do |form| %>
        <% if currency.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

            <ul>
            <% currency.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :symbol %>
          <%= form.text_field :symbol, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.number_field :user_id, value: current_user.id, class: 'form-control', type: 'hidden' %>
        </div>

        <div class="field">
          <%= form.label :invested_at %>
          <%= form.text_field :invested_at, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :amount_owned %>
          <%= form.text_field :amount_owned, class: 'form-control' %>
        </div>

        <br />

        <div class="actions">
          <%= form.submit "Add currency", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/currencies/_form.html.erb
<div class="panel panel-default container-3">
  <div class="panel-heading">
    <h3 class="panel-title">New currency</h3>
  </div>
  <div class="panel-body">
    <div class="form-group">


      <%= form_with(model: currency, local: true) do |form| %>
        <% if currency.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

            <ul>
            <% currency.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :symbol %>
          <%= form.text_field :symbol, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.number_field :user_id, value: current_user.id, class: 'form-control', type: 'hidden' %>
        </div>

        <div class="field">
          <%= form.label :invested_at %>
          <%= form.text_field :invested_at, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :amount_owned %>
          <%= form.text_field :amount_owned, class: 'form-control' %>
        </div>

        <br />

        <div class="actions">
          <%= form.submit "Add currency", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/currencies/edit.html.erb
<%= render 'edit', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Symbol</th>
      <th>Price</th>
      <th>1hr</th>
      <th>24hrs</th>
      <th>7d</th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <% if currency.user_id == current_user.id %>
        <% if currency.symbol %>
          <% currency.symbol = currency.symbol.upcase %>
        <% end %>
        <tr>
        <% for x in @portfolio_currency %>
          <% if currency.symbol == x["symbol"] %>
            <td><%= x["rank"] %></td>
            <td><%= link_to x["name"], currency %></td>
            <td><%= currency.symbol %></td>
            <td>$<%= x["price_usd"] %></td>
            <td><%= x["percent_change_1h"] %>%</td>
            <td><%= x["percent_change_24h"] %>%</td>
            <td><%= x["percent_change_7d"] %>%</td>
          <% end %>
        <% end %>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br><br>

<strong>Portfolio profit/loss: </strong> <%= number_to_currency(@profit_loss) %>

<br><br><br>

<%= link_to 'Add Currency', new_currency_path, class: 'btn btn-primary' %>

app/views/currencies/new.html.erb
<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<% for x in @show_currency %>
	<% if @currency.symbol.upcase == x["symbol"] %>
		<% currency_price = x["price_usd"] %>
		<% currency_name = x["name"] %>
		<% currency_rank = x["rank"] %>
	<% end %>
<% end %>

<div class="panel panel-default container-3">
  <div class="panel-heading">
    <h3 class="panel-title">Your <%= currency_name %>
</h3>
  </div>
  <div class="panel-body">
    <div class="form-group">

		<p>
		  <strong>Currency:</strong>
		  <%= @currency.symbol.upcase %>
		</p>

		<p>
		  <strong>Invested at:</strong>
			$<%= currency_price = x["price_usd"] %>
		</p>
		<p>
		  <strong>Rank:</strong>
			<%= currency_rank %>
		</p>

		<p>
		  <strong>In your portfolio:</strong>
		  <%= @currency.amount_owned %> <%= @currency.symbol.upcase %>
		</p>


    </div>
  </div>
  <div class="panel-footer">
	<%= link_to 'Edit', edit_currency_path(@currency) %> |
	<%= link_to 'Delete', currency_path(@currency), method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Back', currencies_path %>
  </div>
</div>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-warning alert-dismissable">
	<button class="close" data-dismiss="alert">
		<i class="glyphicon glyphicon-remove-circle"></i>
	</button>
		<%= content_tag(:div, msg) %>
	</div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag ('/logo.png'), class: 'logo' %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
    		<li><%= link_to "Home", root_path %></li>
    		<li><%= link_to "About", home_about_path %></li>
        <li><%= link_to "Lookup", home_lookup_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Portfolio", currencies_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h3>Currency Lookup</h3>
<br />
<%= form_tag home_index_path, :method => 'POST' do %>
	<%= text_field_tag 'sym', nil, placeholder: 'Enter crypto symbol', size: 50 %>
	<%= submit_tag 'Lookup Quotes', class: "btn btn-primary" %>
<% end %> 
<br />

<% if @symbol %>
	<% for x in @lookup_coin %>
		<% if @symbol == x["symbol"] %>
			<%= x["name"] %>: $<%= x["price_usd"] %><br />
			Rank: <%= x["rank"] %><br /><br />
		<% end %>
	<% end %>
<% end %>

app/views/home/lookup.html.erb
<h3>Currency Lookup</h3>
<br />
<%= form_tag home_lookup_path, :method => 'POST' do %>
	<%= text_field_tag 'sym', nil, placeholder: 'Enter crypto symbol', size: 50 %>
	<%= submit_tag 'Lookup Quotes' %>
<% end %> 
<br />

<%= @symbol %>

<% if @symbol %>
	<% for x in @lookup_coin %>
		<% if @symbol == x["symbol"] %>
			<%= x["name"] %>: $<%= x["price_usd"] %><br />
			Rank: <%= x["rank"] %><br /><br />
		<% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tekuila</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container-2">
      <%= render 'home/flash' %>
      <%= yield %>
    </div>
  </body>
</html>